# Generated by Django 5.0.6 on 2024-06-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_rename_cliente_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
