# Generated by Django 5.0.6 on 2024-06-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0003_alter_clients_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='nombre',
        ),
        migrations.AddField(
            model_name='clients',
            name='name',
            field=models.CharField(default='Sin Nombre', max_length=30, verbose_name='Nombre del Cliente'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='direction',
            field=models.CharField(max_length=50, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='telephone',
            field=models.CharField(max_length=9, verbose_name='Número de Telefono'),
        ),
    ]
